#include "aerial/bot_sort.hpp"
#include <opencv2/imgproc.hpp>
#include <cmath>
#include <iostream>
#include <stdexcept>
#include <string>

namespace {

void require(bool value, const std::string& message) {
    if (!value) throw std::runtime_error(message);
}

aerial::Detection detection(float x, float score = 0.9f, int cls = 0) {
    return {{x, 20, 50, 40}, score, cls};
}

aerial::TrackerConfig config() {
    aerial::TrackerConfig result;
    result.gmc_method = "none";
    return result;
}

void lifecycle() {
    auto cfg = config();
    cfg.track_buffer_seconds = 0.5;
    cfg.prediction_output_seconds = 0.1;
    aerial::BotSort tracker(cfg);
    auto result = tracker.update({detection(10)}, {}, 0);
    require(result.size() == 1 && result[0].detection_updated, "First-frame activation");
    const auto id = result[0].track_id;
    result = tracker.update({detection(11, 0.2f)}, {}, 1.0 / 30);
    require(result.size() == 1 && result[0].track_id == id && result[0].detection_updated,
            "Low-score second-stage association must preserve ID");
    result = tracker.update({}, {}, 2.0 / 30);
    require(result.size() == 1 && !result[0].detection_updated && result[0].seconds_since_update > 0,
            "Short-term prediction must be explicitly marked");
    result = tracker.update({detection(13)}, {}, 3.0 / 30);
    require(result.size() == 1 && result[0].track_id == id && result[0].detection_updated,
            "High-score detection must reactivate a lost ID");
    result = tracker.update({}, {}, 0.25);
    require(result.empty(), "Prediction output horizon must be respected");
    result = tracker.update({detection(15)}, {}, 0.61);
    require(result.empty(), "Expired ID cannot revive and new late track needs confirmation");
    result = tracker.update({detection(15)}, {}, 0.64);
    require(result.size() == 1 && result[0].track_id != id, "New confirmed ID after expiration");
}

void tentative_and_class_gate() {
    aerial::BotSort tracker(config());
    tracker.update({}, {}, 0);
    require(tracker.update({detection(10)}, {}, 0.03).empty(), "Late new tracks start unconfirmed");
    require(tracker.update({}, {}, 0.06).empty(), "Unmatched unconfirmed track must be removed");
    require(tracker.update({detection(10)}, {}, 0.09).empty(), "New tentative track");
    auto result = tracker.update({detection(10)}, {}, 0.12);
    require(result.size() == 1, "Second high-score hit confirms tentative track");
    const auto previous_id = result[0].track_id;
    result = tracker.update({detection(10, 0.9f, 1)}, {}, 0.15);
    require(result.size() == 1 && result[0].track_id == previous_id && !result[0].detection_updated,
            "Different class must not update existing track");
    result = tracker.update({detection(10, 0.9f, 1)}, {}, 0.18);
    require(result.size() == 2 && result[1].class_id == 1 && result[1].track_id != previous_id,
            "Class-specific tracks must not be removed as duplicates");
}

void global_assignment() {
    aerial::BotSort tracker(config());
    auto result = tracker.update({detection(0), detection(20)}, {}, 0);
    require(result.size() == 2, "Initialize two tracks");
    const auto first_id = result[0].track_id;
    result = tracker.update({detection(5), detection(-10)}, {}, 1.0 / 30);
    require(result.size() == 2 && result[0].track_id == first_id && result[0].bbox.x < 0 &&
            result[1].bbox.x < 20 && result[1].bbox.x > 0,
            "Global optimum must assign -10 to first track and 5 to second (greedy fails)");
}

void upstream_kalman_fixture() {
    // Generated by unmodified upstream kalman_filter.py at the pinned commit.
    // Reproduce with third_party/botsort/generate_kalman_fixture.py.
    const double expected[][4] = {
        {3.471074380165291, 20.0, 50.0, 40.0},
        {7.18380824959435, 20.0, 50.0, 40.0},
        {9.811417764901286, 20.76325118516251, 53.05300474065004, 41.52650237032502},
        {12.042660479886166, 21.028897862837585, 54.11559145135034, 42.05779572567517}
    };
    aerial::BotSort tracker(config());
    tracker.update({detection(0)}, {}, 0);
    const std::vector<std::vector<aerial::Detection>> observations = {
        {detection(4)}, {detection(8)}, {{{10, 21, 54, 42}, 0.9f, 0}}, {}
    };
    for (int i = 0; i < 4; ++i) {
        const auto result = tracker.update(observations[i], {}, (i + 1) / 30.0);
        require(result.size() == 1 && result[0].track_id == 1, "Upstream fixture ID");
        const double actual[] = {result[0].bbox.x, result[0].bbox.y,
                                 result[0].bbox.width, result[0].bbox.height};
        for (int k = 0; k < 4; ++k)
            require(std::abs(actual[k] - expected[i][k]) < 1e-4,
                    "XYWH Kalman output differs from pinned Python upstream");
    }
}

void duplicate_cleanup() {
    auto cfg = config();
    cfg.match_thresh = 0.1f;
    aerial::BotSort tracker(cfg);
    tracker.update({detection(10, 0.99f)}, {}, 0);
    // Score-fused cost .2 exceeds the strict first-stage threshold, creating
    // a tentative duplicate; upstream lifespan rule keeps the old lost ID.
    auto result = tracker.update({detection(10, 0.8f)}, {}, 1.0 / 30);
    require(result.size() == 1 && result[0].track_id == 1 && !result[0].detection_updated,
            "Tracked/lost duplicate cleanup must preserve longer/equal-lived lost ID");
    result = tracker.update({detection(10, 0.99f)}, {}, 2.0 / 30);
    require(result.size() == 1 && result[0].track_id == 1 && result[0].detection_updated,
            "Reactivation after duplicate cleanup must not create duplicate outputs");
}

void timestamps_and_skips() {
    aerial::BotSort short_gap(config()), long_gap(config());
    for (int i = 0; i < 3; ++i) {
        short_gap.update({detection(static_cast<float>(4 * i))}, {}, i / 30.0);
        long_gap.update({detection(static_cast<float>(4 * i))}, {}, i / 30.0);
    }
    auto shorter = short_gap.update({}, {}, 3.0 / 30);
    auto longer = long_gap.update({}, {}, 5.0 / 30);
    require(shorter.size() == 1 && longer.size() == 1 && longer[0].bbox.x > shorter[0].bbox.x + 1,
            "Prediction must use source timestamp elapsed time, including skipped frames");
    bool rejected = false;
    try { long_gap.update({detection(99)}, {}, 4.0 / 30); }
    catch (const std::invalid_argument&) { rejected = true; }
    require(rejected, "Out-of-order image timestamp must be rejected");
    rejected = false;
    try { long_gap.update({}, {}, 5.0 / 30); }
    catch (const std::invalid_argument&) { rejected = true; }
    require(rejected, "Duplicate image timestamp must be rejected");
    auto result = long_gap.update({detection(20)}, {}, 6.0 / 30);
    require(result.size() == 1 && result[0].detection_updated && result[0].track_id == 1,
            "Rejected results must not mutate tracking state");
}

void gmc_translation() {
    aerial::TrackerConfig cfg;
    aerial::BotSort tracker(cfg);
    cv::Mat source(240, 320, CV_8UC3);
    cv::RNG rng(20260924);
    rng.fill(source, cv::RNG::UNIFORM, 0, 256);
    cv::GaussianBlur(source, source, {3, 3}, 0.6);
    cv::Mat shifted;
    const cv::Matx23d translation(1, 0, 10, 0, 1, 6);
    cv::warpAffine(source, shifted, translation, source.size());
    tracker.update({detection(80)}, source, 0);
    const auto result = tracker.update({}, shifted, 1.0 / 30);
    require(result.size() == 1 && !result[0].detection_updated, "GMC prediction output");
    require(std::abs(result[0].bbox.x - 90) < 1.0 && std::abs(result[0].bbox.y - 26) < 1.0,
            "Sparse optical flow must compensate image translation");
    // Featureless images must safely fall back to identity, including size changes.
    tracker.update({}, cv::Mat::zeros(241, 321, CV_8UC3), 2.0 / 30);
    tracker.update({}, cv::Mat::zeros(241, 321, CV_8UC3), 3.0 / 30);
}

void invalid_configuration() {
    auto cfg = config();
    cfg.nominal_fps = 0;
    bool rejected = false;
    try { aerial::BotSort tracker(cfg); }
    catch (const std::invalid_argument&) { rejected = true; }
    require(rejected, "Zero nominal frame rate must fail configuration validation");
}

} // namespace

int main() {
    try {
        cv::setNumThreads(1); // Match the application's explicit OpenCV thread budget.
        lifecycle();
        tentative_and_class_gate();
        global_assignment();
        upstream_kalman_fixture();
        duplicate_cleanup();
        timestamps_and_skips();
        gmc_translation();
        invalid_configuration();
        std::cout << "BoT-SORT tests passed\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "BoT-SORT test failed: " << error.what() << '\n';
        return 1;
    }
}
